allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
nodeVersion: "22.22.2"
saveExact: true
overrides:
  unhead@<2.1.13: ^2.1.13
minimumReleaseAgeExclude:
  - lint-staged@17.0.7
  - tinyexec@1.2.4
