<template>
	<NavigationMenuRoot
		aria-label="Меню сайта"
		:unmount-on-hide="false"
		disable-hover-trigger
		disable-pointer-leave-close
		class="mx-auto hidden text-sm leading-none font-bold sm:flex md:text-base"
		@update:model-value="(val) => $emit('update:modelValue', val)"
	>
		<NavigationMenuList class="flex h-full items-center gap-3.75 md:gap-5 lg:gap-10 xl:gap-12.5">
			<NavigationMenuItem
				v-for="(item, index) in items"
				:key="index"
				:class="index >= 3 ? 'hidden lg:[display:revert]' : ''"
			>
				<NavigationMenuLink
					v-if="item.type === 'link'"
					as-child
				>
					<UiLink
						v-bind="item.link"
						class="hover:text-toned uppercase"
					/>
				</NavigationMenuLink>

				<template v-else-if="item.type === 'button'">
					<NavigationMenuTrigger
						as-child
						class="transition-[font-size] data-[state=closed]:[font-size:inherit] data-[state=open]:text-base lg:data-[state=open]:text-xl data-[state=closed]:[&_.icon]:size-3 data-[state=closed]:[&_.icon]:rotate-0 data-[state=open]:[&_.icon]:size-4 data-[state=open]:[&_.icon]:rotate-180"
					>
						<UiButton class="hover:text-toned items-center gap-0.75 uppercase md:gap-1.25">
							<span>{{ item.label }}</span>
							<Icon
								name="assist:chevron-down"
								class="inline-flex transition-[width_height_rotate]"
							/>
						</UiButton>
					</NavigationMenuTrigger>
					<NavigationMenuContent class="bg-default fixed inset-x-0 top-15 z-10 hidden h-full overflow-hidden sm:block md:top-25">
						<HeaderMenu :items="item.items ?? []" />
					</NavigationMenuContent>
				</template>
			</NavigationMenuItem>
		</NavigationMenuList>

		<Teleport to="body">
			<NavigationMenuViewport />
		</Teleport>
	</NavigationMenuRoot>
</template>

<script setup lang="ts">
import type { UiLinkProps } from "~/components/ui/UiLink.vue";
import type { HeaderMenuProps } from "./HeaderMenu.vue";

defineEmits(["update:modelValue"]);

type NavItem = {
	type: "link" | "button";
	link?: UiLinkProps;
	label?: string;
} & Partial<HeaderMenuProps>;

const items: NavItem[] = [
	{
		type: "link",
		link: {
			label: "Главная",
		},
	},
	{
		type: "button",
		label: "Предметы",
		items: [
			{
				label: "Боеприпасы",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Конструкции",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Одежда",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Компоненты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Электричество",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Оружие",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Ресурсы",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Еда",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Инструменты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Ловушки",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Медикаменты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Развлечение",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Разное",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
		],
	},
	{
		type: "button",
		label: "Мир",
		items: [
			{
				label: "Боеприпасы",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Конструкции",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Одежда",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Компоненты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Электричество",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Оружие",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Ресурсы",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Еда",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Инструменты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Ловушки",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Медикаменты",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Развлечение",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
			{
				label: "Разное",
				sections: [
					{
						label: "Обувь",
						items: [
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
						],
					},
					{
						label: "Верх",
						items: [
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
						],
					},
					{
						label: "Низ",
						items: [
							{ label: "Buckshot" },
							{ label: "5.56 Rifle Ammo" },
							{ label: "HV 5.56 Rifle Ammo" },
							{ label: "Incendiary 5.56 Rifle Ammo" },
							{ label: "Антирадиационный костюм" },
							{ label: "Pistol Bullet" },
							{ label: "Премиальный ресурс для крафта высшего уровня" },
							{ label: "HV Pistol Ammo" },
							{ label: "Баллон с воздухом" },
							{ label: "Улучшенный рацион для долгих экспедиций" },
							{ label: "Waterwell NPC Jumpsuit" },
							{ label: "Incendiary Pistol Bullet" },
							{ label: "Explosive 5.56 Rifle Ammo" },
							{ label: "Slug" },
							{ label: "Incendiary Shell" },
							{ label: "Handmade Shell" },
						],
					},
					{
						label: "Ботинки",
						items: [
							{ label: "Rocket" },
							{ label: "High Velocity Rocket" },
							{ label: "HE Grenade" },
							{ label: "Smoke" },
							{ label: "Shotgun Round" },
						],
					},
					{
						label: "Головные уборы",
						items: [
							{ label: "Wooden Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Bone Arrow" },
							{ label: "Fire Arrow" },
							{ label: "HV Arrow" },
							{ label: "SAM Ammo" },
							{ label: "Turret Ammo" },
						],
					},
				],
			},
		],
	},
	{
		type: "link",
		link: {
			label: "Утилиты",
		},
	},
	{
		type: "link",
		link: {
			label: "О нас",
		},
	},
];
</script>
